import Head from 'next/head'
import { GetStaticProps, InferGetStaticPropsType } from 'next'

import Markdown from '@/components/markdown'
import { readFileSync } from 'fs'
import { rootPath } from '@/util/path'

type Props = {
  describe: string
}

export default function Home(props: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>零清单</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main>
        <Markdown content={props.describe} />
      </main>
    </>
  )
}

export const getStaticProps: GetStaticProps<Props> = () => {
  const homeDescriptionPath = rootPath() + '/src/doc/project-describe.md'
  const describe = readFileSync(homeDescriptionPath, 'utf-8')
  return {
    props: {
      describe: describe
    }
  }
}
